#20 C++ Client - Field format
Klebert-Engineering/zswag pull request #29
Opened 2021-03-08 12:09 UTC by KRE02

### Changes

* Added support for missing field formats.
* Added support for encoding non-buffer and non-string fields.
* Added unit-tests, testing field encoding.

### Review Checklist

- [ ] The changes are understood.
- [ ] The changes are well documented.
- [ ] The changes have been tested.

*Do FF-Merge, as we will rebase the cpp-client branch when done.*

2021-03-09 17:40 UTC, KRE02 commented on libs/zswagcl/src/base64.cpp
> -    return encode(base64url_chars, bytes_to_encode, in_len);
Important!

2021-03-18 08:53 UTC, KRE02 commented
The tests seem to crash on windows. @josephbirkner, could you please investigate further?

2021-03-18 09:00 UTC, josephbirkner commented
> 
> 
> The tests seem to crash on windows. @josephbirkner, could you please investigate further?

Sure, will do.

2021-03-18 14:18 UTC, josephbirkner requested changes
Enjoyed reading the code a lot! Left a few suggestions and questions. 👇

2021-03-18 14:18 UTC, josephbirkner commented on libs/zswagcl/include/zswagcl/zsr-client.hpp
> +class ZsrClient : public ::zserio::IService
ZSWAGCL_EXPORT

2021-03-18 14:18 UTC, josephbirkner commented on libs/zswagcl/src/base64.cpp
> +    while (str.back() == '=')
Is removing the padding safe? In base64url, is the padding char really '='? 🤔

2021-03-18 14:18 UTC, josephbirkner commented on libs/zswagcl/src/zsr-client.cpp
> +        return helper.object(std::move(map));
Clang-Tidy: Passing result of std::move() as a const reference argument; no move will actually happen

2021-03-18 14:18 UTC, josephbirkner commented on libs/zswagcl/src/zsr-client.cpp
> +        std::vector<std::string> array;
```suggestion
        std::vector<std::string> array;
        array.reserve(value.size());
```

2021-03-18 14:18 UTC, josephbirkner commented on libs/zswagcl/src/zsr-client.cpp
> +        std::vector<std::string> array;
```suggestion
        std::vector<std::string> array;
        array.reserve(value.size());
```

2021-03-18 14:18 UTC, josephbirkner commented on libs/zswagcl/src/zsr-client.cpp
> +            auto size = meta->bitSize(object);
Is this logic necessary? Zserio should be smart enough to do that on its own. Then you can use `writer`:
```cpp
size_t size;
const uint8_t* buffer = writer.getWriteBuffer(size);
```

2021-03-18 14:18 UTC, josephbirkner commented on libs/zswagcl/src/zsr-client.cpp
> +        if (field == "" || field == "*")
```suggestion
        if (field == ZSERIO_REQUEST_PART_WHOLE)
```

2021-03-18 14:18 UTC, josephbirkner commented on libs/zswagcl/src/zsr-client.cpp
> +        if (field == "" || field == "*")
Empty request part meaning whole request is not necessarily helpful I think, because this prevents you from adding parameters to your API that are not related to the zserio request object.

2021-03-18 14:18 UTC, josephbirkner commented on libs/zswagcl/CMakeLists.txt
> +  src/base64.hpp
Small thing: I prefer grouping by file type first (probably because it looks a bit prettier).

2021-03-18 14:18 UTC, josephbirkner commented on libs/zswagcl/src/openapi-parser.cpp
> +                            OpenAPIConfig::Path& path)
Concerns line 134 below: Use `ZSERIO_OBJECT_CONTENT_TYPE`

2021-03-18 14:18 UTC, josephbirkner commented on libs/zswagcl/src/openapi-client.cpp
> +        throw std::runtime_error("Could not find method for name");
Please include the missing method name in the error message.

2021-03-18 14:18 UTC, josephbirkner commented on libs/zswagcl/src/openapi-client.cpp
> +        throw std::runtime_error("Could not find method for name");
Generally, the error message could be a bit longer: `"The operation 'abc' is not part of the used OpenApi service specification."` or so

2021-03-18 14:18 UTC, josephbirkner commented on libs/zswagcl/src/openapi-client.cpp
> +            throw std::runtime_error("Unsupported HTTP type");
Please include the name of the unsupported HTTP method type and the operation id in the error message.

2021-03-18 14:18 UTC, josephbirkner commented on libs/zswagcl/src/openapi-client.cpp
> +        uri.addQuery(std::move(key), std::move(value));
`std::move` has no effect on a const value.

2021-03-18 14:18 UTC, josephbirkner commented on libs/zswagcl/src/openapi-client.cpp
> +            throw std::runtime_error(stx::replace_with("Could not find path parameter for name '?'", "?", ident));
Please include the full path string or the operation id in the error message.

2021-03-18 14:18 UTC, josephbirkner commented on libs/zswagcl/src/openapi-client.cpp
> +                                                                   ParameterValueHelper&)>& fun)
Maybe use a more descriptive name for `fun`, like `parameterValueFun` or so.

2021-03-18 14:18 UTC, josephbirkner commented on libs/zswagcl/src/openapi-client.cpp
> +                            const _Fun fun)
Maybe use a more descriptive name for `fun`, like `parameterValueFun` or so.

2021-03-18 14:18 UTC, josephbirkner commented on libs/zswagcl/src/openapi-client.cpp
> +                        const _Fun fun)
Maybe use a more descriptive name for `fun`, like `parameterValueFun` or so.

2021-03-18 14:18 UTC, josephbirkner commented on libs/zswagcl/src/openapi-client.cpp
> +        pos = begin + replacement.size();
```suggestion
        pos = end;
```

2021-03-18 14:18 UTC, josephbirkner commented on libs/zswagcl/include/zswagcl/openapi-parameter-helper.hpp
> +            std::array<char, 30> buffer;
The longest possible string here is 16+1 for the sign (+1 for null?)?

2021-03-18 14:18 UTC, josephbirkner commented on libs/zswagcl/include/zswagcl/openapi-parameter-helper.hpp
> +        std::swap(((uint8_t *)&v)[i], ((uint8_t *)&v)[sizeof(v) - 1u - i]);
Clever!

2021-03-18 14:18 UTC, josephbirkner commented on libs/zswagcl/src/openapi-parameter-helper.cpp
> +std::string join(const std::map<std::string, std::string>& map,
Small thing: Maybe call this one `mapToString`  or `joinMap` or `fold` or so. The generic "join" is very associated with the usual string join, and it becomes a bit hard to discern the two down below in the code.

2021-03-18 14:18 UTC, josephbirkner commented on libs/zswagcl/src/openapi-parameter-helper.cpp
> +std::string join(const std::map<std::string, std::string>& map,
If only C++ had named arguments 🙄

2021-03-18 14:18 UTC, josephbirkner commented on libs/zswagcl/src/openapi-parameter-helper.cpp
> +                return {{std::make_pair(param.ident, join(v, ",", ","))}};
The explicit call to make_pair is not necessary right?

2021-03-18 14:35 UTC, KRE02 commented on libs/zswagcl/src/openapi-client.cpp
> +        pos = begin + replacement.size();
Nope, not correct. `end` = End of the placeholder (`}` + 1) but the replacement string can be shorter/longer and moves the tail of the original string.

2021-03-18 14:44 UTC, KRE02 commented on libs/zswagcl/src/base64.cpp
> +    while (str.back() == '=')
Base64 padding char is `=`. Base64url removes that:
https://en.wikipedia.org/wiki/Base64#Decoding_Base64_with_padding
https://en.wikipedia.org/wiki/Base64#URL_applications

2021-03-18 14:58 UTC, josephbirkner commented on libs/zswagcl/src/openapi-client.cpp
> +        pos = begin + replacement.size();
Ah, right.

2021-03-18 15:00 UTC, josephbirkner commented on libs/zswagcl/src/base64.cpp
> +    while (str.back() == '=')
Thanks!

2021-03-18 17:37 UTC, josephbirkner requested changes
Two more remarks: I think body blobs should only happen when the body content type is `application/x-zserio-object`.

2021-03-18 17:37 UTC, josephbirkner commented on libs/zswagcl/include/zswagcl/openapi-config.hpp
> +        bool bodyRequestObject = true;
This should be false by default. It will be set to true if the path spec has `application/x-zserio-object` as body content type.

2021-03-18 17:37 UTC, josephbirkner commented on libs/zswagcl/test/src/zsr-client.cpp
> +            REQUIRE(type == "application/binary");
Since the path spec below does not have `application/x-zserio-object` for body content, this test fails if the `bodyRequestObject` default value is changed to `false` as suggested

2021-03-19 10:47 UTC, johannes-wolf commented on libs/zswagcl/include/zswagcl/zsr-client.hpp
> +class ZsrClient : public ::zserio::IService
CMakes `EXPORT_ALL_SYMBOLS` is on, so no explicit export should be necessary.

2021-03-19 10:57 UTC, josephbirkner commented on libs/zswagcl/src/openapi-parser.cpp
>                      throw std::runtime_error("Unsupported body content type");
```suggestion
                    throw std::runtime_error("Unsupported body content type");
                else
                    path.bodyRequestObject = true;
```

2021-03-19 11:13 UTC, josephbirkner approved these changes
💸

2021-03-19 11:16 UTC, merged