Server: Support x-zserio-request-part [WIP]
Klebert-Engineering/zswag pull request #35
Opened 2021-03-18 10:35 UTC by josephbirkner

### Changes

Fixes #15

### Review Checklist

- [ ] The changes are understood.
- [ ] The changes are well documented.
- [ ] The changes have been tested.

2021-03-18 11:20 UTC, KRE02 requested changes

2021-03-18 11:20 UTC, johannes-wolf commented on libs/zswag/test/client.cpp
> +    std::cout << zsr::get(response, "value").get<double>().value();
Append `<< "\n"`.

2021-03-18 11:20 UTC, johannes-wolf commented on libs/zswagcl/include/zswagcl/http-service.hpp
> +        bool bodyRequestObject = false; // TODO: Not used
Why this got changed?

2021-03-18 11:20 UTC, johannes-wolf commented on libs/zswag/test/client.cpp
> +    auto openApiConfig = fetchOpenAPIConfig(specUrl, httpClientRef);
Remove line 20.
Change line 21 to `*httpClient`.

2021-03-18 11:20 UTC, johannes-wolf commented on libs/zswag/test/client.cpp
> +    auto specUrl = std::string(argv[1]);
Check `argc` or `argv[1] != nullptr`.

2021-03-18 11:20 UTC, johannes-wolf commented on libs/zswag/request.py
> +    if fmt == OpenApiConfigParamFormat.STRING or \
String format is _not_ base64! It's just a byte stream, that could be string representation or binary data – depending on the type of the zserio-field.

2021-03-18 11:20 UTC, johannes-wolf commented on libs/zswag/request.py
> +        return bytes.fromhex(s)
Integers hex encoding is not 2ers-comp. and can even include a “-” prefix for negative numbers!

2021-03-18 15:33 UTC, josephbirkner commented on libs/zswagcl/include/zswagcl/http-service.hpp
> +        bool bodyRequestObject = false; // TODO: Not used
Just for testing while waiting for #29

2021-03-24 22:39 UTC, KRE02 commented on libs/zswag/test/test_integration.bash
> +      sleep 10
Why is this needed?

2021-03-25 07:49 UTC, josephbirkner commented on libs/zswag/test/test_integration.bash
> +      sleep 10
The server startup can take between 1-10 seconds. Normally it's <5, but in one case on macOS it took longer than 5.

2021-03-25 09:58 UTC, KRE02 approved these changes

2021-03-25 09:58 UTC, KRE02 commented on libs/zswag/test/client.cpp
> +    ) mutable -> void
Nitpick: remove `mutable`

2021-03-25 09:59 UTC, merged